create table
  public."Content" (
    title text not null,
    description text null,
    uuid uuid not null,
    size bigint not null,
    rating integer null,
    uploaded date not null,
    views smallint not null default '0'::smallint,
    constraint contents_pkey primary key (uuid)
  ) tablespace pg_default;

create table
  public."Content_Tags" (
    content_uuid uuid not null,
    tag text not null,
    constraint Content_Tags_pkey primary key (content_uuid, tag),
    constraint public_Content_uuid_fkey foreign key (content_uuid) references "Content" (uuid) on delete cascade
  ) tablespace pg_default;

create table
  public."User" (
    id bigint generated by default as identity,
    email text not null,
    nickname text not null,
    password text not null,
    joined date not null,
    interests text[] not null,
    constraint users_pkey primary key (id),
    constraint users_email_key unique (email)
  ) tablespace pg_default;

create table
  public."User_Interests" (
    user_id bigint not null,
    interest text not null,
    constraint User_Interests_pkey primary key (user_id, interest),
    constraint public_User_Interests_user_id_fkey foreign key (user_id) references "User" (id) on delete cascade
  ) tablespace pg_default;